name: Deploy Firebase Functions on GitHub push

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest

    env:
      working-directory: ./functions

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Install dependencies and Firebase CLI
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.0.2
          run_install: |
            - args: []
              cwd: ${{env.working-directory}}
            - args: [--global, firebase-tools]

      - name: Deploy to Firebase
      - name: deploy
        run: firebase deploy --token ${{ secrets.GCLOUD_TOKEN }}